import { MatchStatus } from '@/features/match/models/match.types'

export const STALE_TIME: number = 1000 * 60 * 5 // 5 minutes

export const TYPING_DELAY: number = 700

export const MATCH_STATUSES: MatchStatus[] = ['upcoming', 'live', 'finished']

export const FRANCE_PLAYERS: string[] = [
  'Mbappé',
  'Mateta',
  'Thuram',
  'Dembélé',
  'Barcola',
  'Doué',
  'Olise',
  'Cherki',
  'Tchouaméni',
  'Akliouche',
  'Koné',
  'Zaïre-Emery',
  'Rabiot',
  'Kanté',
  'Koundé',
  'Saliba',
  'Gusto',
  'Digne',
  'Lucas Hernández',
  'Konaté',
  'Upamecano',
  'Lacroix',
  'Théo Hernández',
  'Risser',
  'Samba',
  'Maignan',
]

export const SPAIN_PLAYERS: string[] = [
  'Oyarzabal',
  'Muñoz',
  'Iglesias',
  'Torres',
  'Merino',
  'Ruiz',
  'Lamine Yamal',
  'Baena',
  'Williams',
  'Gavi',
  'Pedri',
  'Olmo',
  'Rodri',
  'Zubimendi',
  'Pino',
  'Porro',
  'Pubill',
  'Eric García',
  'Llorente',
  'Cubarsí',
  'Cucurella',
  'Grimaldo',
  'Laporte',
  'Joan García',
  'Simón',
  'Raya',
]

export const ENGLAND_PLAYERS: string[] = [
  'Kane',
  'Toney',
  'Watkins',
  'Madueke',
  'Bellingham',
  'Rashford',
  'Eze',
  'Rice',
  'Anderson',
  'Mainoo',
  'Jordan Henderson',
  'Rogers',
  'Gordon',
  'Saka',
  'James',
  'Quansah',
  'Spence',
  'Stones',
  'Konsa',
  'Burn',
  'Guéhi',
  `O'Reilly`,
  'Chalobah',
  'Trafford',
  'Dean Henderson',
  'Pickford',
]

export const ARGENTINA_PLAYERS: string[] = [
  'Messi',
  'Lautaro Martínez',
  'Alvarez',
  'López',
  'Lo Celso',
  'Fernández',
  'Mac Allister',
  'Almada',
  'Palacios',
  'Barco',
  'Paz',
  'De Paul',
  'Paredes',
  'González',
  'Simeone',
  'Capaldo',
  'Lisandro Martínez',
  'Romero',
  'Montiel',
  'Medina',
  'Tagliafico',
  'Otamendi',
  'Molina',
  'Senesi',
  'Giay',
  'Ovando',
  'Musso',
  'Rulli',
  'Emiliano Martínez',
  'Beltrán',
]
