import type { Metadata } from 'next'
import { Geist, Geist_Mono, Roboto_Slab, Noto_Sans } from 'next/font/google'
import '@/shared/styles/globals.css'
import { cn } from '@/shared/lib/utils'
import AppProvider from '@/shared/components/ui/app-provider'

const notoSansHeading = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-heading',
})

const robotoSlab = Roboto_Slab({ subsets: ['latin'], variable: '--font-serif' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-serif',
        robotoSlab.variable,
        notoSansHeading.variable
      )}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
          <main className="flex flex-1 w-full max-w-3xl flex-col items-center justify-between pt-8 pb-32 px-8 md:px-16 bg-white dark:bg-black sm:items-start">
            <AppProvider>{children}</AppProvider>
          </main>
        </div>
      </body>
    </html>
  )
}
